# Generated by Django 4.1.2 on 2023-03-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdetail_b2b'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='review',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
