# Generated by Django 4.1.2 on 2023-03-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feedbacks_name_feedbacks_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='landmark',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='state',
            new_name='street',
        ),
    ]
