# Generated by Django 4.1.2 on 2023-04-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_landmark_userdetail_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2b',
            name='registration_id',
        ),
        migrations.RemoveField(
            model_name='b2b',
            name='select_user',
        ),
        migrations.AddField(
            model_name='b2b',
            name='email',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2b',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2b',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2b',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
