# Generated by Django 4.1.2 on 2023-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
